bridge.py
mqtt_connector.py
mqtt_echo_client.py
network_connector.py
serial_connector.py
tests.py

Fb 11 splitted requests

---

gadgetlib.py
toolkits/bridge_remote_control.py

Fb 17 gadget sync

---

json_schemas/request_basic_structure.json
mqtt_connector.py
network_connector.py
serial_connector.py

Fb 12 network connector json schema

---

bridge.py
console_toolkit.py
json_schemas/bridge_gadget_update_request.json
json_schemas/bridge_heartbeat_request.json
json_schemas/bridge_sync_request.json
serial_connector.py

Fb 14 bride request validation

---

network/rest_server.py
smarthome_bridge/api_manager.py
smarthome_bridge/bridge.py
tests/bridge/test_api_manager.py

#33 Fixed the payload bug

---

.github/workflows/tests.yml

Fb 39 fix pipeline failure

---

gadget_publishers/gadget_publisher.py
gadget_publishers/gadget_publisher_homebridge.py
gadget_publishers/homebridge_encoder.py
gadget_publishers/homebridge_network_connector.py
gadgets/gadget_factory.py
gadgets/lamp_neopixel_basic.py
network/mqtt_connector.py
network/mqtt_server_client.py
smarthome_bridge/api_decoder.py
smarthome_bridge/api_manager.py
smarthome_bridge/api_manager_delegate.py
smarthome_bridge/bridge.py
smarthome_bridge/bridge_main.py
smarthome_bridge/gadget_manager.py
smarthome_bridge/gadget_pubsub.py
smarthome_bridge/gadget_status_supplier.py
smarthome_bridge/gadget_update_information.py
test_helpers/dummy_api_delegate.py
test_helpers/gadget_fixtures.py
tests/bridge/gadget_publishers/test_gadget_publisher_homebridge.py
tests/bridge/gadget_publishers/test_homebridge_encoder.py
tests/bridge/gadgets/test_gadget_factory.py
tests/bridge/test_api_manager.py

Fb 46 gadget manager characteristic update

---

.github/workflows/repo_checks.yml

#50 Updated Workflow

---

.github/workflows/repo_checks.yml

#54 Added workaround for github actions bug

---

client_config_manager.py
smarthome_bridge/api_decoder.py
smarthome_bridge/api_manager.py
tests/bridge/test_api_manager.py
tests/test_client_config_manager.py

Fb 8 add api endpoint to save configs

---

.github/issue_template/bug.yml
.github/issue_template/change.yml
.github/issue_template/feature.yml

Fb 43 add issue templates

---

.github/workflows/repo_checks.yml

#62 Switched to reusable workflow

---

.github/workflows/repo_checks.yml

#61 Unified workflow

---

smarthome_bridge/api_decoder.py
smarthome_bridge/api_encoder.py
smarthome_bridge/client.py
tests/bridge/test_api_encoder_decoder.py
tests/bridge/test_api_manager.py
tests/bridge/test_client.py
tests/bridge/test_client_manager.py

Fb 53 add api version to client

---

bridge_update_manager.py
repository_manager.py
smarthome_bridge/api_encoder.py
smarthome_bridge/api_manager.py

Fb 18 bridge update via api

---

bridge_update_manager.py
smarthome_bridge/bridge_main.py

#67 api version bug

---

.run/PyTest NoNetwork.run.xml
README.md
bridge_update_manager.py
chip_flasher.py
repository_manager.py
smarthome_bridge/api_encoder.py
smarthome_bridge/api_manager.py
smarthome_bridge/characteristic.py
tests/bridge/test_characteristic.py

Fb 69 repo manager init

---

auth_manager.py
clients/client_controller.py
network/rest_server.py
smarthome_bridge/api_manager.py
tests/bridge/gadget_publishers/test_gadget_publisher_homebridge.py
tests/bridge/test_api_manager.py
tests/test_auth_manager.py
tests/test_user_manager.py
user_manager.py

Fb 72 rest manager uris

---

network/mqtt_server_client.py
network/serial_server_client.py

#74 Added auth to MQTT and serial

---

.run/PyTest Bridge.run.xml
.run/PyTest.run.xml
network/request.py
smarthome_bridge/api_encoder.py
smarthome_bridge/api_manager.py
smarthome_bridge/api_manager_delegate.py
smarthome_bridge/bridge.py
smarthome_bridge/bridge_main.py
smarthome_bridge/network_manager.py
tests/bridge/test_bridge.py

Fb 79 bridge meta container

---

tests/test_repository_manager.py
utils/bridge_update_manager.py
utils/repository_manager.py

Fb 87 detatched head update

---

gadget_publishers/homebridge_decoder.py

#89 Fixing crash on bools

---

Pipfile
bridge_main.py
network/mqtt_connector.py
network/rest_server.py
smarthome_bridge/bridge.py
tests/network/test_rest_server.py

Fb 92 env file

---

clients/client_controller.py
network/mqtt_server_client.py
network/network_server_client.py
network/request.py
network/rest_server.py
network/rest_server_request_manager.py
network/serial_server_client.py
network/socket_server_client.py
network/split_request_handler.py
smarthome_bridge/api_manager.py
smarthome_bridge/network_manager.py
test_helpers/dummy_network_connector.py
tests/test_json_validator.py
tests/test_pubsub.py
toolkit/bridge_remote_control.py
toolkit/direct_connection_toolkit.py

Fb 71 request direction

---

conftest.py
smarthome_bridge/api/request_handler_gadget.py
smarthome_bridge/api/response_creator.py
smarthome_bridge/api_encoders/gadget_api_encoder.py
test_helpers/dummy_gadget.py
test_helpers/dummy_gadget_update_applier.py
tests/api/managers/test_req_handler_gadgets.py
tests/api/managers/test_req_handler_gadgets_gadget_update.py
tests/bridge/gadgets/test_gadget.py

Fb 106 gadget request manager tests

---

bridge_main.py
smarthome_bridge/bridge_launcher.py
tests/bridge/test_bridge_launcher.py
tests/test_user_manager.py
utils/user_manager.py

#107 Default user is now being created, if flag is set
